language: ruby
cache: bundler
stages:
- name: unit
  if: type IN (pull_request)
- name: integration
  if: type IN (pull_request)
- name: periodic
  if: type IN (push)
jobs:
  include:
  # unit
  - stage: unit
    name: unit tests
    script: bundle exec rake test:unit
    rvm:
    - 2.3
    - jruby-9.1.7
  - stage: unit
    name: pronto code review
    script: |
      git remote add upstream https://github.com/gooddata/gooddata-ruby.git
      git fetch upstream master
      bundle exec pronto run -c upstream/master --exit-code
  - stage: unit
    name: sdk vcr tests
    script: VCR_RECORD_MODE=none bundle exec rake test:sdk
    rvm: jruby-9.1.7
  - stage: unit
    name: sdk vcr tests (project)
    script: VCR_RECORD_MODE=none bundle exec rake test:project
    rvm: jruby-9.1.7
  # integration
  - &lcm-integration-tests
    stage: integration
    name: lcm integration tests
    script: |
      bundle exec rake -f lcm.rake docker:build
      bundle exec rake -f lcm.rake docker:bundle
      bundle exec rake -f lcm.rake test:integration:docker
    rvm:
    - jruby-9.1.7
  - stage: integration
    name: sdk integration tests
    script: bundle exec rake test:sdk
    rvm: jruby-9.1.7
    env: VCR_ON=false
  - stage: integration
    name: sdk integration tests (project)
    script: bundle exec rake test:project
    env: VCR_ON=false
    rvm: jruby-9.1.7
  # periodic
  - <<: *lcm-integration-tests
    name: lcm integration tests (staging 3)
    env: GD_ENV=development
